#!/bin/bash

docker network create yii-basic

docker run -d --name app-basic --net yii-basic --net-alias app --volume /var/www/hello/basic:/var/www/html/ php-yii

docker run -d --name nginx-basic --net yii-basic --net-alias server --volume /var/www/hello/basic:/var/www/html/ -p 8080:80 nginx-yii
